[package]
name = "doc-server"
version = "0.1.0"
edition = "2024"
description = "Automated local documentation server for Rust workspaces and toolchains with built-in routing"
authors = ["Viacheslav Modestov <viacheslav.modestov@gmail.com>"]

[dependencies]
ignore = "0.4"
axum = "0.8.9"
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.7.0", features = ["fs"] }
clap = { version = "4.4", features = ["derive"] }


[profile.release]
opt-level = 3
lto = "thin"
debug = false
strip = "none"
debug-assertions = false
overflow-checks = false
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false

